JCF: Issue #510: add in gcc 14.3, even the November 2025 version of folly doesn't build against gcc 15.2
This is due to greater stringency in how gcc 15.2 handles templates; the specific error is

/tmp/root/spack-stage/spack-stage-folly-2025.11.24.00-xccq7iggewxd6v4rjz3rn22pcmmupa4d/spack-src/folly/container/detail/F14SetFallback.h:262:16: error: call of overloaded
'find(const std::basic_string_view<char>&)' is ambi guous 1898 262 |
return find(key) != this->end(); 1899 | ~~~~^~~~~ 1900
/tmp/root/spack-stage/spack-stage-folly-2025.11.24.00-xccq7iggewxd6v4rjz3rn22pcmmupa4d/spack-src/folly/container/detail/F14SetFallback.h:262:16: note: there are 10 candidates